image: adaptavist/all-tools:openjdk11-latest-1.4.6
definitions:
  check: &check
    name: Check HCL
    script:
      - (echo ${PIPELINE_GIT_PRIVATE_KEY} | base64 -d >> ~/.ssh/id_rsa) && chmod 0600 ~/.ssh/id_rsa
      - terraform fmt -check -recursive -diff

  integration-tests: &integration-tests
    name: Integration Tests
    script:
      - (apk add --update go)
      - (cd test && AWS_ACCESS_KEY_ID="${TF_TEST_AWS_ACCESS_KEY_ID}" AWS_SECRET_ACCESS_KEY="${TF_TEST_AWS_SECRET_ACCESS_KEY}" go test -timeout 60m)

  compliance: &compliance
    name: Compliance
    image:
      name: bridgecrew/checkov:latest
      entrypoint:
        - '/usr/bin/env'
        - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    script:
      - checkov -d . -s

  release: &release
    name: Release
    image: node:13
    caches:
      - node
    script:
      - npm install --save-dev
      - npx semantic-release -r ${BITBUCKET_GIT_HTTP_ORIGIN}

pipelines:
  default:
    - step: *check
    - step: *compliance
    - step: *integration-tests
  branches:
    master:
      - step: *check
      - step: *compliance
      - step: *integration-tests
      - step: *release